version: "3.9"

services:
  app:
    container_name: food-ordering-api
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=2762002
      POSTGRES_DB=food_ordering_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
